### PR TITLE
Working on iOS

### PR DESCRIPTION
**Pull request by coreyar**
# Description
Updates the project to run on ios

- Renames font-files so the names are consistent across both platforms
- Disables flipper so that use-frameworks can be used with `react-native-file-selector` [Issue](    https://github.com/prscX/react-native-file-selector/issues/71)
- Creates a constants for font families

### CODE REVIEW

**Comment by coreyar** [comment]
I opened this PR as a draft because I am currently unable to test on Android. It appears that the project requires JVM 11 and I currently have 14 installed. 

@farshed Can you let me know what version of java you are using so I can try to narrow down the issue?

**Comment by farshed** [comment]
Nice work @coreyar. You should know that I'm working on a custom file system interface (based on react-native-fs) that would allow us to not be dependant on react-native-file-selector anymore. Btw, I'm on version 8 of Java and Android doesn't support higher Java versions afaik

**Comment by coreyar** [comment]
@farshed would you like to take this PR in the meantime so other iOS issues could be ironed out or should I close it?

**Comment by coreyar** [comment]
Also, you can build Android apps on versions of Java greater than 8. I believe 8 is the minimum. I currently use 14 for other RN Android apps. I believe it comes down to the gradle setup

**Pull request closed without merging**
